rtl/axil_gpio.sv
rtl/ai_accelerator/ai_accelerator_top.sv
rtl/ai_accelerator/mac_unit.sv
rtl/ai_accelerator/ai_accel_axi_slave.sv
rtl/ai_accelerator/ai_dma_master.sv
rtl/my_fifo.v
rtl/axi_interconnect_custom.sv
rtl/dummy_axi_slave.sv
rtl/axi_ram.sv
ips/rtl/axil_adapter_rd.v
ips/rtl/axi_axil_adapter.v
ips/rtl/axil_crossbar_wr.v
ips/rtl/axi_vfifo_enc.v
ips/rtl/axil_register_wr.v
ips/rtl/axil_reg_if_rd.v
ips/rtl/axi_fifo_rd.v
ips/rtl/axi_cdma_desc_mux.v
ips/rtl/axi_interconnect.v
ips/rtl/axil_cdc_rd.v
ips/rtl/axi_ram.v
ips/rtl/axi_axil_adapter_rd.v
ips/rtl/axi_register_rd.v
ips/rtl/axi_ram_wr_rd_if.v
ips/rtl/axil_register_rd.v
ips/rtl/axil_cdc_wr.v
ips/rtl/axi_dma_wr.v
ips/rtl/axil_register.v
ips/rtl/axil_ram.v
ips/rtl/axi_dp_ram.v
ips/rtl/axil_adapter_wr.v
ips/rtl/axi_crossbar.v
ips/rtl/axi_vfifo_raw.v
ips/rtl/axi_fifo_wr.v
ips/rtl/axi_crossbar_wr.v
ips/rtl/axi_ram_rd_if.v
ips/rtl/axi_dma.v
ips/rtl/axil_crossbar_rd.v
ips/rtl/axi_vfifo_raw_wr.v
ips/rtl/axi_vfifo_raw_rd.v
ips/rtl/axi_cdma.v
ips/rtl/axil_crossbar.v
ips/rtl/priority_encoder.v
ips/rtl/axil_dp_ram.v
ips/rtl/axi_adapter.v
ips/rtl/arbiter.v
ips/rtl/axi_dma_desc_mux.v
ips/rtl/axi_dma_rd.v
ips/rtl/axil_reg_if.v
ips/rtl/axi_register.v
ips/rtl/axil_interconnect.v
ips/rtl/axil_reg_if_wr.v
ips/rtl/axi_adapter_wr.v
ips/rtl/axi_crossbar_addr.v
ips/rtl/axil_crossbar_addr.v
ips/rtl/axi_fifo.v
ips/rtl/axi_ram_wr_if.v
ips/rtl/axi_register_wr.v
ips/rtl/axi_vfifo.v
ips/rtl/axil_cdc.v
ips/rtl/axil_adapter.v
ips/rtl/axi_crossbar_rd.v
ips/rtl/axi_axil_adapter_wr.v
ips/rtl/axi_vfifo_dec.v
ips/rtl/axi_adapter_rd.v
soc_top.sv
