./ips/core/rtl/include/cv32e40p_apu_core_pkg.sv
./ips/core/rtl/include/cv32e40p_fpu_pkg.sv
./ips/core/rtl/include/cv32e40p_pkg.sv
./ips/core/rtl/cv32e40p_aligner.sv
./ips/core/rtl/cv32e40p_alu_div.sv
./ips/core/rtl/cv32e40p_alu.sv
./ips/core/rtl/cv32e40p_apu_disp.sv
./ips/core/rtl/cv32e40p_compressed_decoder.sv
./ips/core/rtl/cv32e40p_controller.sv
./ips/core/rtl/cv32e40p_core.sv
./ips/core/rtl/cv32e40p_cs_registers.sv
./ips/core/rtl/cv32e40p_decoder.sv
./ips/core/rtl/cv32e40p_ex_stage.sv
./ips/core/rtl/cv32e40p_ff_one.sv
./ips/core/rtl/cv32e40p_fifo.sv
./ips/core/rtl/cv32e40p_fp_wrapper.sv
./ips/core/rtl/cv32e40p_hwloop_regs.sv
./ips/core/rtl/cv32e40p_id_stage.sv
./ips/core/rtl/cv32e40p_if_stage.sv
./ips/core/rtl/cv32e40p_int_controller.sv
./ips/core/rtl/cv32e40p_load_store_unit.sv
./ips/core/rtl/cv32e40p_mult.sv
./ips/core/rtl/cv32e40p_obi_interface.sv
./ips/core/rtl/cv32e40p_popcnt.sv
./ips/core/rtl/cv32e40p_prefetch_buffer.sv
./ips/core/rtl/cv32e40p_prefetch_controller.sv
./ips/core/rtl/cv32e40p_register_file_ff.sv
./ips/core/rtl/cv32e40p_register_file_latch.sv
./ips/core/rtl/cv32e40p_sleep_unit.sv
./ips/core/rtl/cv32e40p_top.sv
./rtl/axi_lib/rtl/arbiter.v
./rtl/axi_lib/rtl/axi_adapter_rd.v
./rtl/axi_lib/rtl/axi_adapter.v
./rtl/axi_lib/rtl/axi_adapter_wr.v
./rtl/axi_lib/rtl/axi_axil_adapter_rd.v
./rtl/axi_lib/rtl/axi_axil_adapter.v
./rtl/axi_lib/rtl/axi_axil_adapter_wr.v
./rtl/axi_lib/rtl/axi_cdma_desc_mux.v
./rtl/axi_lib/rtl/axi_cdma.v
./rtl/axi_lib/rtl/axi_crossbar_addr.v
./rtl/axi_lib/rtl/axi_crossbar_rd.v
./rtl/axi_lib/rtl/axi_crossbar.v
./rtl/axi_lib/rtl/axi_crossbar_wr.v
./rtl/axi_lib/rtl/axi_dma_desc_mux.v
./rtl/axi_lib/rtl/axi_dma_rd.v
./rtl/axi_lib/rtl/axi_dma.v
./rtl/axi_lib/rtl/axi_dma_wr.v
./rtl/axi_lib/rtl/axi_dp_ram.v
./rtl/axi_lib/rtl/axi_fifo_rd.v
./rtl/axi_lib/rtl/axi_fifo.v
./rtl/axi_lib/rtl/axi_fifo_wr.v
./rtl/axi_lib/rtl/axi_interconnect.v
./rtl/axi_lib/rtl/axil_adapter_rd.v
./rtl/axi_lib/rtl/axil_adapter.v
./rtl/axi_lib/rtl/axil_adapter_wr.v
./rtl/axi_lib/rtl/axil_cdc_rd.v
./rtl/axi_lib/rtl/axil_cdc.v
./rtl/axi_lib/rtl/axil_cdc_wr.v
./rtl/axi_lib/rtl/axil_crossbar_addr.v
./rtl/axi_lib/rtl/axil_crossbar_rd.v
./rtl/axi_lib/rtl/axil_crossbar.v
./rtl/axi_lib/rtl/axil_crossbar_wr.v
./rtl/axi_lib/rtl/axil_dp_ram.v
./rtl/axi_lib/rtl/axil_interconnect.v
./rtl/axi_lib/rtl/axil_ram.v
./rtl/axi_lib/rtl/axil_reg_if_rd.v
./rtl/axi_lib/rtl/axil_reg_if.v
./rtl/axi_lib/rtl/axil_reg_if_wr.v
./rtl/axi_lib/rtl/axil_register_rd.v
./rtl/axi_lib/rtl/axil_register.v
./rtl/axi_lib/rtl/axil_register_wr.v
./rtl/axi_lib/rtl/axi_ram_rd_if.v
./rtl/axi_lib/rtl/axi_ram.v
./rtl/axi_lib/rtl/axi_ram_wr_if.v
./rtl/axi_lib/rtl/axi_ram_wr_rd_if.v
./rtl/axi_lib/rtl/axi_register_rd.v
./rtl/axi_lib/rtl/axi_register.v
./rtl/axi_lib/rtl/axi_register_wr.v
./rtl/axi_lib/rtl/axi_vfifo_dec.v
./rtl/axi_lib/rtl/axi_vfifo_enc.v
./rtl/axi_lib/rtl/axi_vfifo_raw_rd.v
./rtl/axi_lib/rtl/axi_vfifo_raw.v
./rtl/axi_lib/rtl/axi_vfifo_raw_wr.v
./rtl/axi_lib/rtl/axi_vfifo.v
./rtl/axi_lib/rtl/priority_encoder.v
soc_top.sv
