./dummy_cpu.sv
./rtl/axil_gpio.sv
./rtl/ai_accelerator/ai_accelerator_top.sv
./rtl/ai_accelerator/mac_unit.sv
./rtl/ai_accelerator/ai_accel_axi_slave.sv
./rtl/ai_accelerator/ai_dma_master.sv
./rtl/mcu_top.sv
./rtl/my_fifo.v
./rtl/axi_interconnect_custom.sv
./rtl/dummy_axi_slave.sv
./rtl/axi_ram.sv
./cv32e40p_register_file.sv
./obi_to_axil_bridge.sv
./simple_ram.sv
./axil_dummy_slave.sv
./axi_interfaces.sv
./tb/mcu_tb.sv
./tb/mac_unit_tb.sv
./tb/ai_dma_master_tb.sv
./soc_top.sv
./dummy_slave.sv
./ips/axi_axil_adapter.v
./axi_ram.sv
